gocd-server:
  labels:
    gocd.role: server
#  tty: true
  image: gocd/gocd-server:16.10.0
  environment:  
    - AGENT_KEY=123456789abcdef
  volumes_from:
  - gocd-volume
  environment:
  - SERVER_MEM=${mem_initial}m
  - SERVER_MAX_MEM=${mem_max}m
  ports:
  - ${public_port}:8153
  - ${ssh_port}:8154
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: gocd-volume
gocd-volume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
  - ${volume_work}:/opt/go-server/work
  volume_driver: ${volume_driver}
  entrypoint: /bin/true
  image: busybox
go-agent:
  image: gocd/gocd-agent:16.10.0
  links:
    - go-server
