.catalog:
  name: gocd-server
  version: 16.12.0-rancher2
  description: |
    (Experimental) Gocd server.
  maintainer: "Mikael Sennerholm <mikael@Sennerholm.net>"
  minimum_rancher_version: v0.59.0
  uuid: cdlab-0
  questions:
    - variable: "config_url"
      description: "Url to download initial go config from (by curl)"
      label: "config url:"
      required: false
      default: "https://github.com/sennerholm/doodleshop/blob/master/go-pipelineconf.xml"
      type: "string"
    - variable: public_port
      description: "public port to access the gocd server"
      label: "Public Port"
      required: true
      default: "8153"
      type: "int"
    - variable: ssh_port
      description: "port for remote access of go-agents"
      label: "SSH Port"
      required: true
      default: "8154"
      type: "int"
    - variable: "mem_initial"
      description: "Initial java memory in Mb"
      label: "Initial memory:"
      required: true
      default: 512
      type: "int"
    - variable: "mem_max"
      description: "Max java memory in Mb"
      label: "Max memory:"
      required: true
      default: 1024
      type: "int"
    - variable: "volume_work"
      description: "Work volume to save goserver data"
      label: "Work volume:"
      required: true
      default: "/var/lib/docker/go-server-work"
      type: "string"
    - variable: "volume_driver"
      label: "Driver volume:"
      description: |
        Choose the volume driver to use.
      default: local
      required: true
      type: enum
      options:
        - local
        - convoy-gluster
go-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 8153
    interval: 5000
    unhealthy_threshold: 5
    request_line: GET /go/agents HTTP/1.0
    healthy_threshold: 2
    response_timeout: 5000
go-agent:
  scale: 2